version: '3.5'

services:
  app:
    build: ./
    container_name: laravel_vue
#    restart: always
#    user: ${CURRENT_UID} #CURRENT_UID=$(id -u):$(id -g) docker-compose up -d
    ports:
      - 8000:8000
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./:/var/www
    depends_on:
      - db
    links:
      - db:db
    networks:
      - laravel_vue_network

  db:
    image: mysql:5.7.22
#    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'laravel_ui'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - laravel_vue_network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
#    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel_vue_network

networks:
  laravel_vue_network:
    name: laravel_vue_network
    driver: bridge
